-- Baseline schema for home-manager, generated from the initial Hibernate schema.
-- From here on the schema is managed by Flyway; JPA entities are validated
-- against it (spring.jpa.hibernate.ddl-auto: validate).

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    family_id bigint NOT NULL,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);
ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.chore (
    id bigint NOT NULL,
    assignee_name character varying(255),
    assignee_user_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    done boolean NOT NULL,
    due_date date,
    recurrence character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    family_id bigint NOT NULL,
    CONSTRAINT chore_recurrence_check CHECK (((recurrence)::text = ANY ((ARRAY['NONE'::character varying, 'DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying])::text[])))
);
ALTER TABLE public.chore ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chore_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.deadline (
    id bigint NOT NULL,
    amount numeric(38,2),
    category character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    due_date date NOT NULL,
    notes character varying(255),
    paid boolean NOT NULL,
    recurrence character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    family_id bigint NOT NULL,
    CONSTRAINT deadline_category_check CHECK (((category)::text = ANY ((ARRAY['BILL'::character varying, 'TAX'::character varying, 'INSURANCE'::character varying, 'SUBSCRIPTION'::character varying, 'INSPECTION'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT deadline_recurrence_check CHECK (((recurrence)::text = ANY ((ARRAY['NONE'::character varying, 'MONTHLY'::character varying, 'YEARLY'::character varying])::text[])))
);
ALTER TABLE public.deadline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deadline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.document (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    content_type character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    expiry_date date,
    name character varying(255) NOT NULL,
    notes character varying(255),
    original_filename character varying(255),
    size_bytes bigint NOT NULL,
    stored_filename character varying(255) NOT NULL,
    family_id bigint NOT NULL,
    CONSTRAINT document_category_check CHECK (((category)::text = ANY ((ARRAY['IDENTITY'::character varying, 'INSURANCE'::character varying, 'WARRANTY'::character varying, 'CONTRACT'::character varying, 'MANUAL'::character varying, 'MEDICAL'::character varying, 'OTHER'::character varying])::text[])))
);
ALTER TABLE public.document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.expense (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    date date NOT NULL,
    description character varying(255) NOT NULL,
    paid_by_name character varying(255),
    paid_by_user_id bigint,
    family_id bigint NOT NULL,
    CONSTRAINT expense_category_check CHECK (((category)::text = ANY ((ARRAY['GROCERIES'::character varying, 'UTILITIES'::character varying, 'RENT'::character varying, 'TRANSPORT'::character varying, 'HEALTH'::character varying, 'LEISURE'::character varying, 'OTHER'::character varying])::text[])))
);
ALTER TABLE public.expense ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.family (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    invite_code character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);
ALTER TABLE public.family ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.family_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.product (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expiry_date date,
    name character varying(255) NOT NULL,
    quantity numeric(38,2),
    unit character varying(255),
    family_id bigint NOT NULL,
    CONSTRAINT product_category_check CHECK (((category)::text = ANY ((ARRAY['FRESH'::character varying, 'PANTRY'::character varying, 'FROZEN'::character varying, 'BEVERAGES'::character varying, 'OTHER'::character varying])::text[])))
);
ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.shopping_item (
    id bigint NOT NULL,
    added_by character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL,
    purchased boolean NOT NULL,
    quantity numeric(38,2),
    family_id bigint NOT NULL
);
ALTER TABLE public.shopping_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shopping_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.chore
    ADD CONSTRAINT chore_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.deadline
    ADD CONSTRAINT deadline_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.expense
    ADD CONSTRAINT expense_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.family
    ADD CONSTRAINT family_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.shopping_item
    ADD CONSTRAINT shopping_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.family
    ADD CONSTRAINT uk1e2cmk8axdr3l9syhhtrdx63v UNIQUE (invite_code);
ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);
ALTER TABLE ONLY public.shopping_item
    ADD CONSTRAINT fk16hsyl0v0d5m9c8ss7f56g6nd FOREIGN KEY (family_id) REFERENCES public.family(id);
ALTER TABLE ONLY public.document
    ADD CONSTRAINT fk6a630ytu46evlxo91nae76wbk FOREIGN KEY (family_id) REFERENCES public.family(id);
ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkensx2bfyl4ic169gtgi8iqcre FOREIGN KEY (family_id) REFERENCES public.family(id);
ALTER TABLE ONLY public.chore
    ADD CONSTRAINT fkm6d2wjy6ht73nxxr4l0qmihrw FOREIGN KEY (family_id) REFERENCES public.family(id);
ALTER TABLE ONLY public.deadline
    ADD CONSTRAINT fkq2igb0dktqnqshtug8ankcbit FOREIGN KEY (family_id) REFERENCES public.family(id);
ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fkr8pvf9g55i3q45cwdaruqa1g7 FOREIGN KEY (family_id) REFERENCES public.family(id);
ALTER TABLE ONLY public.expense
    ADD CONSTRAINT fktlii7i06d0uulk74yr5hvabfr FOREIGN KEY (family_id) REFERENCES public.family(id);
